### ISSUE TITLE
Add a design doc

### ISSUE THREAD

**Issue by prestonvanloon** [mkosowsk/Mytchmatic#1]
Please write a design doc that outlines the objectives and features of project.

It would be nice to have a full laid out plan so that members of the community can get involved or take ownership of small pieces of the big picture.

**Comment by mkosowsk** [comment]
The excellent @DarrenMills provided a great start to a Design Doc that includes examples from ethstats.net, ethviewer.live, and Parity Browser UI [here](https://docs.google.com/document/d/1sFsieVLQPGpGkpHLTGOou0qvVtJKa8jmcccz0ZtmFp0/edit):

@prestonvanloon do you feel that a Design Doc for Mytchmatic™ would best live as a Google Doc, as part of the README for the project, as a HACKMD, or a different solution? 🤔

Thanks boss! 🙏

**Comment by prestonvanloon** [comment]
Markdown in the README or somewhere else in this repo. Looking good so far!

**Comment by mkosowsk** [comment]
@mkosowsk will confer with @darrenmills and transpose Google Doc to Markdown in the README! 🔥

**Comment by DarrenRM** [comment]
@mkosowsk I'll make a PR soon to add into the README.

Some discussion around which specific features should make it into an MVP seems like a next step. From a UI design perspective, making some decisions on the stack will speak to how it can be styled (bootstrap, d3.js etc).

I'd be interested in hearing more from @prestonvanloon and @mkosowsk about which projects they feel provide a good analogy to the goals here.

**Comment by mkosowsk** [comment]
> @mkosowsk I'll make a PR soon to add into the README.

@DarrenRM great! Updated the README just now so it will be ready for you!

> Some discussion around which specific features should make it into an MVP seems like a next step. From a UI design perspective, making some decisions on the stack will speak to how it can be styled (bootstrap, d3.js etc).

I think using standards like D3.js and Bootstrap make sense, honestly I think the larger the community the better... let's make Mytchmatic™ an inclusive project!

### Goals

For goals, I think the main one is to have a shipped project by Devcon that will represent the health of the BeaconChain per this EXCELLENT [Swagger UI](https://api.prylabs.net/) (Prysmatic team really know what they're doing! 😍)

![Screen Shot 2019-07-16 at 6 30 18 PM](https://user-images.githubusercontent.com/7970539/61334300-dee7ba80-a7f7-11e9-9e01-834bdd9261b6.png)

For Mytchmatic™ we are concerned with the BeaconChain endpoints and I think that it makes sense to have representations for every endpoint per that API but to START, these are the first 3 that make sense to me (@prestonvanloon please add color as you see fit!):

1. /eth/v1alpha1/validators:  Retrieve the current list of active validators.

2. /eth/v1alpha1/validators/balances: Retrieve validator balances for a given set of public keys at a specific epoch in time.
 
3. /eth/v1alpha1/validators/participation: Retrieve the validator participation information for a given epoch.

### Dasboard Examples

> I'd be interested in hearing more from @prestonvanloon and @mkosowsk about which projects they feel provide a good analogy to the goals here.

I think that it makes sense to look to **Web2** for inspiration, but need to have technical dashboard (so something like Airbnb is out).

Honestly I think there is a LARGE overlap between the Twitch streaming community and what will be the Ethereum 2.0 Validator community, I think Twitch dashboard may make sense to look at.

@prestonvanloon @DarrenRM do you each have like a top 3 technical dashboards from Web 2.0 that may make sense to look at for inspiration? 🤔

Thanks! 🙏
